
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["github.com/Sirupsen/logrus"]

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/coreos/go-systemd"
  version = "v16"

[[override]]
  name = "bitbucket.org/ww/goautoneg"
  # Bitbucket doesn't support git protocol, which causes dep to timeout trying to connect
  # force to https url instead
  source = "https://bitbucket.org/ww/goautoneg.git"

[[override]]
  name = "github.com/hashicorp/serf"
  revision = "11bb88abf7b17f0b794b51416a9107d781e95f35"

[[override]]
  # target codec version from etcd, since dep doesn't seem to grab it correctly
  # https://github.com/coreos/etcd/issues/8715#issuecomment-377013707
  name = "github.com/ugorji/go"
  version = "v1.1.1"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "2.0.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.3"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/gravitational/configure"

[[constraint]]
  branch = "master"
  name = "github.com/gravitational/coordinate"

[[constraint]]
  branch = "master"
  name = "github.com/gravitational/go-udev"

[[constraint]]
  name = "golang.org/x/net"
  branch = "release-branch.go1.9"

[[constraint]]
  name = "github.com/gravitational/satellite"
  version = "0.0.17"

[[constraint]]
  name = "github.com/gravitational/trace"
  version = "1.0.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/opencontainers/runc"
  version = "0.1.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = ">=0.7.0, <=64.0.0-g275368f"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  source = "github.com/gravitational/logrus"
  version = "1.0.6"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.0.11"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.9"
