
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["github.com/gravitational/planet/build/*"]

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/coreos/go-systemd"
  version = "v16"

[[override]]
  name = "bitbucket.org/ww/goautoneg"
  # Bitbucket doesn't support git protocol, which causes dep to timeout trying to connect
  # force to https url instead
  source = "https://bitbucket.org/ww/goautoneg.git"

[[override]]
  name = "github.com/hashicorp/serf"
  revision = "11bb88abf7b17f0b794b51416a9107d781e95f35"

[[override]]
  # target codec version from etcd, since dep doesn't seem to grab it correctly
  # https://github.com/coreos/etcd/issues/8715#issuecomment-377013707
  name = "github.com/ugorji/go"
  version = "v1.1.1"

[[override]]
  name = "golang.org/x/sys"
  # Same revision as opencontainers/runc
  revision = "9eafafc0a87e0fd0aeeba439a4573537970c44c7"

[[override]]
  name = "github.com/syndtr/gocapability"
  revision = "33e07d32887e1e06b7c025f27ce52f62c7990bc0"

[[override]]
  name = "github.com/jonboulle/clockwork"
  revision = "62fb9bc030d14f92c58df3c1601e50a0e445edef"

[[constraint]]
  name = "github.com/containerd/console"
  revision = "cb7008ab3d8359b78c5f464cb7cf160107ad5925"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "2.0.0"

[[override]]
  name = "github.com/etcd-io/etcd"
  version = "3.4.3"

[[constraint]]
  name = "github.com/docker/docker"
  version = "=v19.03.6"
  source = "github.com/docker/engine"

[[constraint]]
  branch = "master"
  name = "github.com/gravitational/configure"

[[constraint]]
  name = "github.com/gravitational/coordinate"
  version = "=2.0.0"

[[constraint]]
  version = "=0.0.3"
  name = "github.com/gravitational/etcd-backup"

[[constraint]]
  branch = "master"
  name = "github.com/gravitational/go-udev"

[[constraint]]
  name = "github.com/gravitational/satellite"
  version = "=7.0.8"

[[override]]
  name = "github.com/gravitational/trace"
  version = "=1.1.11"

[[constraint]]
  name = "github.com/opencontainers/selinux"
  version = "=v1.4.0"

[[constraint]]
  name = "github.com/opencontainers/runc"
  version = "=v1.0.0-rc10"

[[override]]
  # required for indirect dependencies of opencontainers/runc
  name = "github.com/pkg/errors"
  version = "=v0.9.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "=v1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  source = "github.com/gravitational/logrus"
  version = "v1.4.3"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  source = "github.com/gravitational/kingpin"
  #version = "=v2.2.7"
  branch = "telekube"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.17.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.17.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.17.3"

[[constraint]]
  name = "k8s.io/kubelet"
  version = "kubernetes-1.17.3"

[[constraint]]
  name = "github.com/fatih/color"
  version = "v1.7.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  revision = "73d445a93680fa1a78ae23a5839bad48f32ba1ee"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[[constraint]]
  name = "github.com/containerd/cgroups"
  revision = "39b18af02c4120960f517a3a4c2588fabb61d02c"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.3.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.2"

[[override]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "29686dbc5559d93fb1ef402eeda3e35c38d75af4"

[[override]]
  name = "google.golang.org/grpc"
  version = "=v1.26.0"
